#!/usr/bin/env bash
set -e

if [ ! -d "$HOME/miniconda3" ]; then
  echo "Installing Miniconda..."
  mkdir -p ~/miniconda3
  curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh -o ~/miniconda3/miniconda.sh
  bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
  rm -rf ~/miniconda3/miniconda.sh
  echo "Miniconda installation complete"
else
  echo "Miniconda already installed"
fi
