#!/usr/bin/env bash
set -e

source 'bin/lib/tools'

dir=$PWD

# Symlink dotfiles
dotfiles="$(ls -Ap source | grep -v deprecated)"

for dotfile in $dotfiles; do
  source_path="$dir/source/$dotfile"
  target_path="$HOME/$dotfile"

  [ -e $source_path ] || continue

  set_link $source_path $target_path
done
