#! /usr/bin/env bash
set -e

sip() {
  # don't exit 1 if brew is installed but newer version exists
  # todo: handle this case by providing interactive option to upgrade the brew
  brew install $1 || :
}

sip_cask() {
 brew install --cask $1 || :
}


if [ ! $(command -v brew) ]; then
  echo "Homebrew not found"
  echo "Installing..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

sip tmux
sip vim
sip wget
sip ack
sip ctags
sip zellij
sip gnupg
sip gawk

sip rbenv
sip ruby-build
sip postgresql@16
sip redis

sip heroku

sip erlang

sip hub

sip coreutils

sip_cask alfred
sip_cask flux
sip_cask rectangle
