#! /usr/bin/env bash
set -e

if [ ! $(command -v brew) ]; then
  echo "Homebrew not found"
  echo "Installing..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew install tmux
brew install vim
brew install wget
brew install ack
brew install ctags

# Install ruby dependencies
brew install postgres
brew install redis
brew install rbenv
brew install heroku

brew install hub

brew cask install alfred
brew cask install flux
brew cask install spectacle
