#!/usr/bin/env bash

entrypoint=$PWD
load_path="$PWD/source/.bats"

fetch_source() {
  (
  if [ -d "$2" ]; then
    echo "Updating $1/$2"
    cd "$2"
    git pull --rebase
  else
    git clone "git://github.com/$1/$2.git" "src"
  fi
  )
}

load() {
  (
  if [ ! -d "$load_path" ]; then
    mkdir $load_path
  fi
  )

  cd $load_path
  fetch_source $1 $2
}

load sstephenson bats

cd $entrypoint
