#! /usr/bin/env bash
set -e

sip() {
  # don't exit 1 if brew is installed but newer version exists
  # todo: handle this case by providing interactive option to upgrade the brew
  brew install $1 || :
}

sip_cask() {
 brew install --cask $1 || :
}


if [ ! $(command -v brew) ]; then
  echo "Homebrew not found"
  echo "Installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install)"
fi

sip awscli
sip colima
sip coreutils
sip ctags
sip docker
sip docker-compose
sip elixir-ls
sip erlang
sip flyctl
sip fzf
sip gawk
sip gcc
sip gh
sip git
sip gnupg
sip graphviz
sip httrack
sip hub
sip hugo
sip ios-deploy
sip jq
sip llvm
sip postgresql@16
sip python@3.12
sip rbenv
sip redis
sip ripgrep
sip ruby-build
sip shellcheck
sip tmux
sip vim
sip wget
sip yt-dlp
sip zellij

sip_cask alfred
sip_cask session-manager-plugin
sip_cask rectangle
